// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

console.log(
  '🔍 DATABASE_URL from env:',
  process.env.DATABASE_URL ? '✅ Found' : '❌ Missing',
);
export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx tsx prisma/seed.ts', // <-- removed --env-file
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
